/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IdManager,
  IdManagerInterface,
} from "../../../contracts/interfaces/IdManager";

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "identifier",
        type: "bytes32",
      },
    ],
    name: "getReputation",
    outputs: [
      {
        internalType: "int256",
        name: "score",
        type: "int256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "id",
        type: "bytes32",
      },
      {
        internalType: "uint256",
        name: "severity",
        type: "uint256",
      },
      {
        internalType: "string",
        name: "metadataCID",
        type: "string",
      },
    ],
    name: "report",
    outputs: [
      {
        internalType: "bytes32",
        name: "reportId",
        type: "bytes32",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IdManager__factory {
  static readonly abi = _abi;
  static createInterface(): IdManagerInterface {
    return new utils.Interface(_abi) as IdManagerInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IdManager {
    return new Contract(address, _abi, signerOrProvider) as IdManager;
  }
}
