/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../common";

export interface CreepzIdManagerInterface extends utils.Interface {
  functions: {
    "getReputation(bytes32)": FunctionFragment;
    "report(bytes32,uint256,string)": FunctionFragment;
    "setReporterRateLimit(uint64)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic: "getReputation" | "report" | "setReporterRateLimit"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "getReputation",
    values: [PromiseOrValue<BytesLike>]
  ): string;
  encodeFunctionData(
    functionFragment: "report",
    values: [
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<string>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "setReporterRateLimit",
    values: [PromiseOrValue<BigNumberish>]
  ): string;

  decodeFunctionResult(
    functionFragment: "getReputation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "report", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setReporterRateLimit",
    data: BytesLike
  ): Result;

  events: {
    "NewReport(bytes32,uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "NewReport"): EventFragment;
}

export interface NewReportEventObject {
  against: string;
  severity: BigNumber;
}
export type NewReportEvent = TypedEvent<
  [string, BigNumber],
  NewReportEventObject
>;

export type NewReportEventFilter = TypedEventFilter<NewReportEvent>;

export interface CreepzIdManager extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: CreepzIdManagerInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    getReputation(
      identifier: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { score: BigNumber }>;

    report(
      id: PromiseOrValue<BytesLike>,
      severity: PromiseOrValue<BigNumberish>,
      metadataCID: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setReporterRateLimit(
      aRate: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  getReputation(
    identifier: PromiseOrValue<BytesLike>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  report(
    id: PromiseOrValue<BytesLike>,
    severity: PromiseOrValue<BigNumberish>,
    metadataCID: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setReporterRateLimit(
    aRate: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    getReputation(
      identifier: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    report(
      id: PromiseOrValue<BytesLike>,
      severity: PromiseOrValue<BigNumberish>,
      metadataCID: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<string>;

    setReporterRateLimit(
      aRate: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<boolean>;
  };

  filters: {
    "NewReport(bytes32,uint256)"(
      against?: null,
      severity?: null
    ): NewReportEventFilter;
    NewReport(against?: null, severity?: null): NewReportEventFilter;
  };

  estimateGas: {
    getReputation(
      identifier: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    report(
      id: PromiseOrValue<BytesLike>,
      severity: PromiseOrValue<BigNumberish>,
      metadataCID: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setReporterRateLimit(
      aRate: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    getReputation(
      identifier: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    report(
      id: PromiseOrValue<BytesLike>,
      severity: PromiseOrValue<BigNumberish>,
      metadataCID: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setReporterRateLimit(
      aRate: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
